name: tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install firefox
    - run: npm install
    - run: git clone --single-branch --branch issue-7159-marionette-connection-timeout https://github.com/cypress-io/cypress.git ./cy-git
    - run: cd ./cy-git && yarn && DEBUG=cypress:* yarn cypress:run --browser=firefox --headless --project=../
